def rot_unscramble(name)
  name.downcase.tr("abcdefghijklmnopqrstuvwxyz", "nopqrstuvwxyzabcdefghijklm").capitalize.split(" ").map(&:capitalize).join(" ")
end

p rot_unscramble("Nqn Ybirynpr")
p rot_unscramble("Tenpr Ubccre")
p rot_unscramble("Nqryr Tbyqfgvar")
p rot_unscramble("Nyna Ghevat")
p rot_unscramble("Puneyrf Onoontr")
p rot_unscramble("Noqhyynu Zhunzznq ova Zhfn ny-Xujnevmzv")
p rot_unscramble("Wbua Ngnanfbss")
p rot_unscramble("Ybvf Unvog")
p rot_unscramble("Pynhqr Funaaba")
p rot_unscramble("Fgrir Wbof")
p rot_unscramble("Ovyy Tngrf")
p rot_unscramble("Gvz Orearef - Yrr")
p rot_unscramble("Fgrir Jbmavnx")
p rot_unscramble("Xbaenq Mhfr")
p rot_unscramble("Fve Nagbal Ubner")
p rot_unscramble("Zneiva Zvafxl")
p rot_unscramble("Lhxvuveb Zngfhzbgb")
p rot_unscramble("Unllvz Fybavzfxv")
p rot_unscramble("Tregehqr Oynapu")
